Update build and release scripts, remove test directories

diff --git a/scripts/build b/scripts/build
--- a/scripts/build
+++ b/scripts/build
@@ -1,11 +1,12 @@
 #!/bin/bash
 
 if [ $# -lt 1 ]; then
-  echo "$0: takes at least one argument: 'get-deps' or 'release <version_number>'"
+  echo "$0: takes at least one argument: 'get-deps', 'clean', 'build fab' or 'build release <version_number>'"
   exit 1
 fi
 
-if [ $1 == "get-deps" ]; then
+# cleans test directories helm_repos
+function clean() {
   echo "cleaning test files"
   echo "cleaning test/fixtures/install/infra/components"
   rm -rf test/fixtures/install/infra/components
@@ -18,29 +19,60 @@ if [ $1 == "get-deps" ]; then
 
   echo "cleaning test/fixtures/install-yaml/helm_repos"
   rm -rf test/fixtures/install-yaml/helm_repos
+}
 
+
+# runs go get ./...
+function get-deps() {
+  clean
   echo "go get ./..."
   go get ./...
 
   echo "get-deps finished"
+}
+
+
+if [ $1 == "get-deps" ]; then
+  get-deps
 fi
 
-if [ $1 == "release" ]; then
-  if [ $# -ne 2 ]; then
-    echo "release takes one argument: the version number of the release."
-    exit 1
+if [ $1 == "clean" ]; then
+  clean
+fi
+
+
+if [ $1 == "build" ]; then
+  
+  # build fabrikate
+  if [ $2 == "fab" ]; then
+     get-deps
+     echo "go build -o fab"
+     go build -o fab
+     echo "finished building fab"
+  fi  
+
+  # gets fabrikate dependencies and builds fabrikate release
+  if [ $2 == "release" ]; then
+    if [ $# -ne 3 ]; then
+      echo "Error: build release takes one argument: the version number of the release."
+      exit 1
+    fi
+
+    get-deps
+
+    rm -rf releases/$3
+    mkdir -p releases/$3
+
+    echo "Building for Mac"
+    GOOS=darwin GOARCH=amd64 go build -o fab
+    zip releases/$3/fab-v$3-darwin-amd64.zip fab
+
+    echo "Building for Linux"
+    GOOS=linux GOARCH=amd64 go build -o fab
+   zip releases/$3/fab-v$3-linux-amd64.zip fab
+
+   echo "Release zip files can be found in releases/$3"
   fi
-
-  rm -rf releases/$2
-  mkdir -p releases/$2
-
-  echo "Building for Mac"
-  GOOS=darwin GOARCH=amd64 go build -o fab
-  zip releases/$2/fab-v$2-darwin-amd64.zip fab
-
-  echo "Building for Linux"
-  GOOS=linux GOARCH=amd64 go build -o fab
-  zip releases/$2/fab-v$2-linux-amd64.zip fab
-
-  echo "Release zip files can be found in releases/$2"
 fi
+
+
